version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${AUTH_DB_NAME},${USER_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - "${AUTH_DB_PORT:-5432}:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./rest/auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${AUTH_DB_NAME}?schema=public
    volumes:
      - ./rest/auth-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${AUTH_SERVICE_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network

  user-service:
    build:
      context: ./rest/user-service
      dockerfile: Dockerfile.dev
    container_name: user-service-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${USER_DB_NAME}?schema=public
    volumes:
      - ./rest/user-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${USER_SERVICE_PORT:-3001}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
